<a href="https://colab.research.google.com/github/Haikoo96/Kpop-Trend-Analysis/blob/master/scraping%20and%20preprocess/Final_filter_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Objective**
- Combining the results by the NER model and regex to finalize the group name per title.

In [3]:
import pandas as pd
import numpy as np
import json
import re
import os
import glob

In [4]:
dir_path = '/content/drive/MyDrive/Colab Notebooks/kpop trend analysis/dataset_raw'
if os.path.exists(dir_path):
  print('path exists')
  csv_paths = glob.glob(os.path.join(dir_path, '*.csv'))

csv_paths

path exists

['/content/drive/MyDrive/Colab Notebooks/kpop trend analysis/dataset_raw/kpop_news_trends.csv',
 '/content/drive/MyDrive/Colab Notebooks/kpop trend analysis/dataset_raw/augmented_dataset.csv',
 '/content/drive/MyDrive/Colab Notebooks/kpop trend analysis/dataset_raw/kpop_augmented_dataset.csv',
 '/content/drive/MyDrive/Colab Notebooks/kpop trend analysis/dataset_raw/kpop_augmented_dataset_v2.csv',
 '/content/drive/MyDrive/Colab Notebooks/kpop trend analysis/dataset_raw/kpop_augmented_dataset_v4.csv',
 '/content/drive/MyDrive/Colab Notebooks/kpop trend analysis/dataset_raw/kpop_augmented_dataset_v6.csv',
 '/content/drive/MyDrive/Colab Notebooks/kpop trend analysis/dataset_raw/kpop_modelcompare_dataset.csv',
 '/content/drive/MyDrive/Colab Notebooks/kpop trend analysis/dataset_raw/temp.csv',
 '/content/drive/MyDrive/Colab Notebooks/kpop trend analysis/dataset_raw/temp - temp.csv',
 '/content/drive/MyDrive/Colab Notebooks/kpop trend analysis/dataset_raw/group_added.csv',
 '/content/drive/MyDrive/Colab Notebooks/kpop trend analysis/dataset_raw/entire_group.csv',
 '/content/drive/MyDrive/Colab Notebooks/kpop trend analysis/dataset_raw/ent_sep_kpop_dataset.csv',
 '/content/drive/MyDrive/Colab Notebooks/kpop trend analysis/dataset_raw/kpop_ent_sep_augemnted.csv',
 '/content/drive/MyDrive/Colab Notebooks/kpop trend analysis/dataset_raw/test.csv',
 '/content/drive/MyDrive/Colab Notebooks/kpop trend analysis/dataset_raw/test_b.csv',
 '/content/drive/MyDrive/Colab Notebooks/kpop trend analysis/dataset_raw/test_c.csv']

In [5]:
json_paths = glob.glob(os.path.join(dir_path, '*.json'))
json_paths

['/content/drive/MyDrive/Colab Notebooks/kpop trend analysis/dataset_raw/normal_char_idol.json',
 '/content/drive/MyDrive/Colab Notebooks/kpop trend analysis/dataset_raw/special_char_idol.json']

In [6]:
with open(json_paths[0], 'r') as file:
  json_a = json.load(file)

with open(json_paths[1], 'r') as file_:
  json_b = json.load(file_)

In [7]:
df = pd.read_csv(csv_paths[-2])
df.drop('Unnamed: 0', axis=1, inplace=True)
df

,title,category,author_name,dates,num comments,num views,PER,LOC,ORG,MISC,group_PER,group_ORG,group_MISC,group_title_a
0,Ryu Jun Yeol back in Korea; confirms dating Ha...,News,Alec06,3/18/2024,5,"3,197","Ryu Jun Yeol, Han So Hee","Korea, Hawaii",NaN,NaN,NaN,NaN,NaN,NaN
1,Ryu Jun Yeol and Han So Hee's unwelcomed start...,News,Alec06,3/18/2024,14,"7,556","Ryu Jun Yeol, Han So Hee",Hawaii,NaN,NaN,NaN,NaN,NaN,NaN
2,DAY6's Dowoon talks post-military growth and n...,News,Alec06,3/18/2024,0,332,NaN,NaN,"DAY6, Dowoon",Fourever,NaN,DAY6,NaN,DAY6
3,"Park Shin Hye reflects on 'Dr. Slump' finale, ...",News,Alec06,3/18/2024,1,"2,018",Park Shin Hye,NaN,NaN,Dr. Slump,NaN,NaN,NaN,NaN
4,"Han Ye Seul to host 'SNL Korea' season 5, spar...",News,Alec06,3/18/2024,2,"1,006",Han Ye Seul,NaN,SN,##L Korea,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1875,THEBLACKLABEL responds to rumors that their ne...,Rumors,Sophie-Ha,02/06/2024,41,"38,809",NaN,NaN,Shinsegae Chaebol Family,NaN,NaN,NaN,NaN,NaN
1876,The Most Infuriating Villains in K-Dramas that...,Original Content,ean1994,02/06/2024,7,"6,224",NaN,NaN,NaN,"Most Inf, ##ting Villains in K - Dramas that y...",NaN,NaN,NaN,NaN
1877,The preliminary audition for selecting new FIF...,News,Sophie-Ha,02/06/2024,21,"9,237",NaN,Singapore,FIFTY FIFTY,NaN,NaN,FIFTY FIFTY,NaN,NaN
1878,TREASURE and their remarkable stage presence,Original Content,Rika-go,02/06/2024,9,"8,249",NaN,NaN,TREASURE,NaN,NaN,TREASURE,NaN,TREASURE
1879,Is this idol the best vocalist among the 4th g...,Discussions,Sophie-Ha,02/06/2024,35,"26,474",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# filter out if all null values assigned under all group_*** columns
cond = (df['group_ORG'].isna()) & (df['group_PER'].isna()) & (df['group_MISC'].isna()) & (df['group_title_a'].isna())

new_df = df[~cond]
new_df.reset_index(drop=True, inplace=True)
new_df

,title,category,author_name,dates,num comments,num views,PER,LOC,ORG,MISC,group_PER,group_ORG,group_MISC,group_title_a
0,DAY6's Dowoon talks post-military growth and n...,News,Alec06,3/18/2024,0,332,NaN,NaN,"DAY6, Dowoon",Fourever,NaN,DAY6,NaN,DAY6
1,The Boyz drops new album 'PHANTASY' Pt.3 and p...,News,Alec06,3/18/2024,0,571,NaN,NaN,The Boyz,PHANTASY,NaN,THE BOYZ,NaN,NaN
2,Candy Shop unveils mini album 'Hashtag#' track...,News,Alec06,3/18/2024,1,684,NaN,New York,Candy Shop,Hashtag,NaN,Candy Shop,HashTag,NaN
3,"BABYMONSTER ready for comeback, set for summer...",News,Alec06,3/18/2024,7,"2,415",NaN,NaN,BABYMONST,NaN,NaN,BABYMONSTER,NaN,BABYMONSTER
4,ZEROBASEONE captivates Japan: sold-out concert...,News,Alec06,3/18/2024,4,"1,256",NaN,Japan,NaN,NaN,NaN,NaN,NaN,ZEROBASEONE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
862,RIIZE Anton's mother becomes a hot topic on on...,News,Sophie-Ha,02/06/2024,15,"30,685",Anton,NaN,NaN,NaN,NaN,NaN,NaN,RIIZE
863,The EXO members are still some of the most pop...,News,Sophie-Ha,02/06/2024,17,"10,078",NaN,China,EXO,NaN,NaN,EXO,NaN,NaN
864,Choi Ye Na talks about coming from a poor fami...,News,Sophie-Ha,02/06/2024,22,"10,273",Choi Ye Na,NaN,NaN,IZ * ONE,NaN,NaN,IZ*ONE,NaN
865,The preliminary audition for selecting new FIF...,News,Sophie-Ha,02/06/2024,21,"9,237",NaN,Singapore,FIFTY FIFTY,NaN,NaN,FIFTY FIFTY,NaN,NaN
866,TREASURE and their remarkable stage presence,Original Content,Rika-go,02/06/2024,9,"8,249",NaN,NaN,TREASURE,NaN,NaN,TREASURE,NaN,TREASURE

In [10]:
group_lst = ['group_PER', 'group_ORG', 'group_MISC', 'group_title_a']
dict(new_df.loc[0, group_lst]).values()

dict_values([nan, 'DAY6', nan, 'DAY6'])

In [11]:
# filter values that have duplicate of their own or just a single string
for ind in new_df.index:
  val_lst = list(dict(new_df.loc[ind, group_lst]).values())
  string_only = [val for val in val_lst if isinstance(val, str)]

  if len(string_only) > 1 and string_only[0] == string_only[1]:
    new_df.at[ind, 'final_group'] = string_only[0]
  elif len(string_only) == 1:
    new_df.at[ind, 'final_group'] = string_only[0]

new_df

<ipython-input-11-4a8041b54c8d>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.at[ind, 'final_group'] = string_only[0]

,title,category,author_name,dates,num comments,num views,PER,LOC,ORG,MISC,group_PER,group_ORG,group_MISC,group_title_a,final_group
0,DAY6's Dowoon talks post-military growth and n...,News,Alec06,3/18/2024,0,332,NaN,NaN,"DAY6, Dowoon",Fourever,NaN,DAY6,NaN,DAY6,DAY6
1,The Boyz drops new album 'PHANTASY' Pt.3 and p...,News,Alec06,3/18/2024,0,571,NaN,NaN,The Boyz,PHANTASY,NaN,THE BOYZ,NaN,NaN,THE BOYZ
2,Candy Shop unveils mini album 'Hashtag#' track...,News,Alec06,3/18/2024,1,684,NaN,New York,Candy Shop,Hashtag,NaN,Candy Shop,HashTag,NaN,NaN
3,"BABYMONSTER ready for comeback, set for summer...",News,Alec06,3/18/2024,7,"2,415",NaN,NaN,BABYMONST,NaN,NaN,BABYMONSTER,NaN,BABYMONSTER,BABYMONSTER
4,ZEROBASEONE captivates Japan: sold-out concert...,News,Alec06,3/18/2024,4,"1,256",NaN,Japan,NaN,NaN,NaN,NaN,NaN,ZEROBASEONE,ZEROBASEONE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
862,RIIZE Anton's mother becomes a hot topic on on...,News,Sophie-Ha,02/06/2024,15,"30,685",Anton,NaN,NaN,NaN,NaN,NaN,NaN,RIIZE,RIIZE
863,The EXO members are still some of the most pop...,News,Sophie-Ha,02/06/2024,17,"10,078",NaN,China,EXO,NaN,NaN,EXO,NaN,NaN,EXO
864,Choi Ye Na talks about coming from a poor fami...,News,Sophie-Ha,02/06/2024,22,"10,273",Choi Ye Na,NaN,NaN,IZ * ONE,NaN,NaN,IZ*ONE,NaN,IZ*ONE
865,The preliminary audition for selecting new FIF...,News,Sophie-Ha,02/06/2024,21,"9,237",NaN,Singapore,FIFTY FIFTY,NaN,NaN,FIFTY FIFTY,NaN,NaN,FIFTY FIFTY
866,TREASURE and their remarkable stage presence,Original Content,Rika-go,02/06/2024,9,"8,249",NaN,NaN,TREASURE,NaN,NaN,TREASURE,NaN,TREASURE,TREASURE

In [ ]:
# new_df.to_csv(os.path.join(dir_path, 'test_c.csv'))